dist: bionic

language: python

sudo: required

script:
  - sudo make install
  - sudo systemctl enable --now nohang
  - sudo systemctl stop nohang.service

  - oom-sort -h
  - oom-sort

  - nohang -h
  - nohang -v

  - nohang -cc /etc/nohang/nohang.conf
  - nohang -cc /etc/nohang/nohang-desktop.conf
  - nohang -cc nohang/test.conf

  - nohang -p
  - sudo nohang -p

  - /bin/sleep 60 &
  - sudo bash -c "nohang -c nohang/test.conf & tail /dev/zero & sleep 30 && pkill python3"
  - sudo cat /var/log/nohang/nohang.log

  - sudo make uninstall
