language: python

script:
  - sudo make install
  - sudo make systemd
  - nohang -h
  - nohang -v
  - nohang -cc /etc/nohang/nohang.conf
  - nohang -p
  - sudo nohang -p
  - oom-sort -h
  - oom-sort
  - sudo make uninstall
